<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jadwal_pelajaran extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jadwal_pelajaran_model');

        // cek user login
        check_login();
    } 

    /*
     * Listing of pengajar
     */
    function index()
    {
        $this->load->model('Kelas_model');
        $data['kelas'] = $this->Kelas_model->get_all_kelas();
        // print_r($data['pengajar']);
        
        $this->load->view('template/header',$data);
        $this->load->view('template/sidebar',$data);
        $this->load->view('jadwal_pelajaran/index',$data);
        $this->load->view('template/footer',$data);
    }

    /*
     * Adding a new pengajar
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array();
			$id_mapel = $this->input->post('id_mapel[]');
			$id_kelas = $this->input->post('id_kelas');
            $id_tahun = $this->input->post('id_tahun');
            
            foreach($id_mapel as $mapel)
            {
                array_push($params, [
                    'id_tahun' => $id_tahun,
                    'id_kelas' => $id_kelas,
                    'id_mapel' => $mapel,
                ]);
            }

            $this->db->insert_batch('jadwal_pelajaran', $params);
            // $pengajar_id = $this->Pengajar_model->add_pengajar($params);
            $this->session->set_flashdata('berhasil', 'Anda berhasil menambah data jadwal pelajaran.</strong>');
            redirect('jadwal_pelajaran/index');
        }
        else
        {
			$this->load->model('Mapel_model');
            $data['all_mapel'] = $this->Mapel_model->get_all_mapel();

			$this->load->model('Kelas_model');
			$data['all_kelas'] = $this->Kelas_model->get_all_kelas();
            
            $this->load->view('template/header',$data);
            $this->load->view('template/sidebar',$data);
            $this->load->view('jadwal_pelajaran/add',$data);
            $this->load->view('template/footer',$data);
        }
    }  

    /*
     * Editing a pengajar
     */
    function edit($id_guru)
    {   
        // check if the pengajar exists before trying to edit it
        $data['pengajar'] = $this->Pengajar_model->get_pengajar($id_guru);
        $data['mapel'] = $this->Pengajar_model->get_mapel_by_id_guru($id_guru);
        // print_r($data['pengajar']);
        // print_r($data['mapel']);
        if(isset($data['pengajar']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_guru' => $this->input->post('id_guru'),
					'id_mapel' => $this->input->post('id_mapel'),
					'id_kelas' => $this->input->post('id_kelas'),
					'id_tahun' => $this->input->post('id_tahun'),
                );

                $this->Pengajar_model->update_pengajar($id_guru,$params);            
                redirect('pengajar/index');
            }
            else
            {
				$this->load->model('Guru_model');
				$data['all_guru'] = $this->Guru_model->get_all_guru();

				$this->load->model('Mapel_model');
				$data['all_mapel'] = $this->Mapel_model->get_all_mapel();

				$this->load->model('Kelas_model');
				$data['all_kelas'] = $this->Kelas_model->get_all_kelas();

                $data['_view'] = 'pengajar/edit';

                if(!empty($data['pengajar'])){
                    $this->load->view('template/header',$data);
                    $this->load->view('template/sidebar',$data);
                    $this->load->view('pengajar/edit',$data);
                    $this->load->view('template/footer',$data);
                } else {
                    redirect('pengajar');
                }
                
            }
        }
        else
            show_error('The pengajar you are trying to edit does not exist.');
    } 

    /*
     * Deleting jadwal
     */
    function remove($id)
    {
        $this->Jadwal_pelajaran_model->remove($id);
        redirect('jadwal_pelajaran');
    }

}