<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kelas extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kelas_model');

        // cek user login
        check_login();
    } 

    /*
     * Listing of kelas
     */
    function index()
    {
        $data['kelas'] = $this->Kelas_model->get_all_kelas();
        
        $data['_view'] = 'kelas/index';
        $this->load->view('template/header',$data);
        $this->load->view('template/sidebar',$data);
        $this->load->view('kelas/index',$data);
        $this->load->view('template/footer',$data);
    }

    /*
     * Adding a new kelas
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required');
		$this->form_validation->set_rules('tingkat','Tingkat','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'tingkat' => $this->input->post('tingkat'),
				'nama' => $this->input->post('nama'),
				'kode_kelas' => $this->input->post('kode_kelas'),
            );
            
            $kelas_id = $this->Kelas_model->add_kelas($params);
            $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data kelas <strong>'.$params['nama'].'</strong>');
            redirect('kelas/index');
        }
        else
        {            
            $data['_view'] = 'kelas/add';
            $this->load->view('template/header',$data);
            $this->load->view('template/sidebar',$data);
            $this->load->view('kelas/add',$data);
            $this->load->view('template/footer',$data);
        }
    }  

    /*
     * Editing a kelas
     */
    function edit($id)
    {   
        // check if the kelas exists before trying to edit it
        $data['kelas'] = $this->Kelas_model->get_kelas($id);
        
        if(isset($data['kelas']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required');
			$this->form_validation->set_rules('tingkat','Tingkat','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'tingkat' => $this->input->post('tingkat'),
					'nama' => $this->input->post('nama'),
					'kode_kelas' => $this->input->post('kode_kelas'),
                );

                $this->Kelas_model->update_kelas($id,$params);
                $this->session->set_flashdata('berhasil', 'Anda berhasil mengubah data kelas <strong>'.$params['nama'].'</strong>');

                redirect('kelas/index');
            }
            else
            {
                $data['_view'] = 'kelas/edit';
                $this->load->view('template/header',$data);
                $this->load->view('template/sidebar',$data);
                $this->load->view('kelas/edit',$data);
                $this->load->view('template/footer',$data);
            }
        }
        else
            show_error('The kelas you are trying to edit does not exist.');
    } 

    /*
     * Deleting kelas
     */
    function remove($id)
    {
        $kelas = $this->Kelas_model->get_kelas($id);

        // check if the kelas exists before trying to delete it
        if(isset($kelas['id']))
        {
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data kelas<strong>'.$kelas['nama'].'</strong>');

            $this->Kelas_model->delete_kelas($id);
            redirect('kelas/index');
        }
        else
            show_error('The kelas you are trying to delete does not exist.');
    }
    
}