<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kompetensi_dasar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kompetensi_dasar_model');
    } 

    /*
     * Listing of kompetensi_dasar
     */
    function index()
    {
        $data['kompetensi_dasar'] = $this->Kompetensi_dasar_model->get_all_kompetensi_dasar();
        $data['mapel'] = $this->Kompetensi_dasar_model->get_mapel();
        
        $data['_view'] = 'kompetensi_dasar/index';
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('kompetensi_dasar/index',$data);
        $this->load->view('template/footer');
    }

    /*
     * Adding a new kompetensi_dasar
     */
    function add()
    {   
        $id_mapel = $this->uri->segment(3);
        $data['mapel'] = $this->Kompetensi_dasar_model->get_id_mapel($id_mapel);
        // tampilkan kelas tingkat berdasarkan mapel yang diajarkan 
        $data['tingkat'] = $this->Kompetensi_dasar_model->get_kelas_tingkat($id_mapel);

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('kompetensi_dasar/add',$data);
        $this->load->view('template/footer');
    }  

    function simpan()
    {
        $params = [
            'id_tahun' => $_SESSION['id_tahun_pelajaran'],
            'id_mapel' => $this->input->post('id_mapel'),
            'tingkat'  => $this->input->post('tingkat'),
            'id_guru' => user_info()['id_guru'],
            'kd' => $this->input->post('kd')
        ];

        $this->Kompetensi_dasar_model->add_kompetensi_dasar($params);
        redirect('kompetensi_dasar');
    }

    /*
     * Editing a kompetensi_dasar
     */
    function edit($id)
    {   
        // check if the kompetensi_dasar exists before trying to edit it
        $data['kompetensi_dasar'] = $this->Kompetensi_dasar_model->get_kompetensi_dasar($id);    
        $data['mapel'] = $this->Kompetensi_dasar_model->get_id_mapel($data['kompetensi_dasar']['id_mapel']);

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('kompetensi_dasar/edit',$data);
        $this->load->view('template/footer');
    } 

    function simpan_edit($id)
    {
        $kd = $this->input->post('kd');
        $params = ['kd' => $kd];
        $this->Kompetensi_dasar_model->update_kompetensi_dasar($id,$params);
        redirect('kompetensi_dasar');
    }

    /*
     * Deleting kompetensi_dasar
     */
    function remove($id)
    {
        $kompetensi_dasar = $this->Kompetensi_dasar_model->get_kompetensi_dasar($id);

        // check if the kompetensi_dasar exists before trying to delete it
        if(isset($kompetensi_dasar['id']))
        {
            $this->Kompetensi_dasar_model->delete_kompetensi_dasar($id);
            redirect('kompetensi_dasar/index');
        }
        else
            show_error('The kompetensi_dasar you are trying to delete does not exist.');
    }
    
}