<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pengajar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pengajar_model');

        // cek user login
        check_login();
    } 

    /*
     * Listing of pengajar
     */
    function index()
    {
        $data['pengajar'] = $this->Pengajar_model->get_all_pengajar();
        // print_r($data['pengajar']);
        
        $data['_view'] = 'pengajar/index';
        $this->load->view('template/header',$data);
        $this->load->view('template/sidebar',$data);
        $this->load->view('pengajar/index',$data);
        $this->load->view('template/footer',$data);
    }

    /*
     * Adding a new pengajar
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array();
            $id_guru = $this->input->post('id_guru');
			$id_mapel = $this->input->post('id_mapel');
			$id_kelas = $this->input->post('id_kelas[]');
            $id_tahun = $this->input->post('id_tahun');
            
            foreach($id_kelas as $kelas)
            {
                array_push($params, [
                    'id_guru' => $id_guru,
                    'id_mapel' => $id_mapel,
                    'id_tahun' => $id_tahun,
                    'id_kelas' => $kelas
                ]);
            }

            $this->db->insert_batch('pengajar', $params);
            // $pengajar_id = $this->Pengajar_model->add_pengajar($params);
            $this->session->set_flashdata('berhasil', 'Anda berhasil menambah data pengajar.</strong>');
            redirect('pengajar/index');
        }
        else
        {
			$this->load->model('Guru_model');
			$data['all_guru'] = $this->Guru_model->get_all_guru();

			$this->load->model('Mapel_model');
            $data['all_mapel'] = $this->Mapel_model->get_all_mapel();

			$this->load->model('Kelas_model');
			$data['all_kelas'] = $this->Kelas_model->get_all_kelas();
            
            $data['_view'] = 'pengajar/add';
            $this->load->view('template/header',$data);
            $this->load->view('template/sidebar',$data);
            $this->load->view('pengajar/add',$data);
            $this->load->view('template/footer',$data);
        }
    }  

    /*
     * Editing a pengajar
     */
    function edit($id_guru)
    {   
        // check if the pengajar exists before trying to edit it
        $data['pengajar'] = $this->Pengajar_model->get_pengajar($id_guru);
        $data['mapel'] = $this->Pengajar_model->get_mapel_by_id_guru($id_guru);
        // print_r($data['pengajar']);
        // print_r($data['mapel']);
        if(isset($data['pengajar']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_guru' => $this->input->post('id_guru'),
					'id_mapel' => $this->input->post('id_mapel'),
					'id_kelas' => $this->input->post('id_kelas'),
					'id_tahun' => $this->input->post('id_tahun'),
                );

                $this->Pengajar_model->update_pengajar($id_guru,$params);            
                redirect('pengajar/index');
            }
            else
            {
				$this->load->model('Guru_model');
				$data['all_guru'] = $this->Guru_model->get_all_guru();

				$this->load->model('Mapel_model');
				$data['all_mapel'] = $this->Mapel_model->get_all_mapel();

				$this->load->model('Kelas_model');
				$data['all_kelas'] = $this->Kelas_model->get_all_kelas();

                $data['_view'] = 'pengajar/edit';

                if(!empty($data['pengajar'])){
                    $this->load->view('template/header',$data);
                    $this->load->view('template/sidebar',$data);
                    $this->load->view('pengajar/edit',$data);
                    $this->load->view('template/footer',$data);
                } else {
                    redirect('pengajar');
                }
                
            }
        }
        else
            show_error('The pengajar you are trying to edit does not exist.');
    } 

    /*
     * Deleting pengajar
     */
    function remove($id)
    {
        $id_guru = $this->uri->segment(4, 0);
        $this->Pengajar_model->delete_pengajar($id);
        redirect('pengajar/edit/'.$id_guru);
    }

    // uji coba
    function update_pengajar()
    {
        $id = $this->input->post('id[]');
        foreach($id as $i){
            $this->db->delete('pengajar', array('id' => $i)); 
        }
        $this->session->set_flashdata('hapus', 'Anda berhasil mengubah data pengajar.</strong>');
        redirect('pengajar');
    }
}