<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Walikelas extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Walikelas_model');
        $this->load->model('Kelas_model');
        $this->load->model('Guru_model');
    } 

    /*
     * Listing of walikelas
     */
    function index()
    {
        $data['guru'] = $this->Guru_model->get_all_guru();
        $data['kelas'] = $this->Kelas_model->get_all_kelas();
        $data['walikelas'] = $this->Walikelas_model->get_all_walikelas();
        
        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('walikelas/index', $data);
        $this->load->view('template/footer', $data);
    }

    function get_all_walikelas()
    {
        $data = $this->Walikelas_model->get_all_walikelas();
        echo json_encode($data);
    }

    // simpan datanya dari form modal
    function add()
    {
        $params = array(
            'id_kelas' => $this->input->post('id_kelas'),
            'id_guru' => $this->input->post('id_guru'),
            'id_tahun' => $_SESSION['id_tahun_pelajaran']
        );

        if($params['id_kelas'] == 0 || $params['id_guru'] == 0){
            echo json_encode($data);
        } else {
            $this->Walikelas_model->add_walikelas($params);
            echo json_encode($data);
        }
    }    
}