<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jadwal_pelajaran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function get_mapel_by_kelas($id)
    {
        return $this->db->select('jadwal_pelajaran.id id_jadwal, mapel.id id_mapel, mapel.nama nama_mapel, mapel.kode kode_mapel, mapel.kelompok kelompok_mapel')
                ->from('jadwal_pelajaran')
                ->join('mapel', 'mapel.id = id_mapel')
                ->where('id_kelas', $id)
                ->get()
                ->result_array();
    }

    function get_mapel_by_kelas_for_rapor($id)
    {
        $this->db->select('mapel.id id_mapel, mapel.nama nama_mapel, mapel.kode kode_mapel, mapel.kelompok kelompok_mapel, kelas.tingkat tingkat');
        $this->db->from('jadwal_pelajaran');
        $this->db->join('kelas', 'kelas.id =jadwal_pelajaran.id_kelas');
        $this->db->join('mapel', 'mapel.id = jadwal_pelajaran.id_mapel');
        $this->db->where('jadwal_pelajaran.id_kelas', $id);
        $db = $this->db->get();
        return $db->result_array();
    }

    function remove($id)
    {
        return $this->db->delete('jadwal_pelajaran',array('id'=>$id));

    }
}