<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pengajar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pengajar by id
     */
    function get_pengajar($id)
    {
        return $this->db->get_where('pengajar',array('id_guru'=>$id))->row_array();
    }
        
    /*
     * Get all pengajar
     */
    function get_all_pengajar()
    {
        $this->db->select('pengajar.*, guru.nama_lengkap');
        $this->db->from('pengajar');
        $this->db->group_by('id_guru');
        $this->db->where('pengajar.id_tahun ='.$_SESSION['id_tahun_pelajaran']);
        $this->db->join('guru', 'guru.id = pengajar.id_guru');
        $this->db->order_by('guru.nama_lengkap', 'asc');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new pengajar
     */
    function add_pengajar($params)
    {
        $this->db->insert('pengajar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pengajar
     */
    function update_pengajar($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('pengajar',$params);
    }
    
    /*
     * function to delete pengajar
     */
    function delete_pengajar($id)
    {
        return $this->db->delete('pengajar',array('id'=>$id));
    }

    // dapatkan semua mapel yang diajarkan berdasarkan id_guru dan id_tahun 
    function get_mapel_by_id_guru($id_guru)
    {
        $this->db->select('pengajar.id as id, pengajar.id_guru, mapel.id as id_mapel, mapel.nama as nama_mapel, mapel.kode as kode_mapel, kelas.nama as nama_kelas');
        $this->db->from('pengajar');
        $this->db->where('pengajar.id_guru ='.$id_guru);
        $this->db->where('pengajar.id_tahun ='.$_SESSION['id_tahun_pelajaran']);
        $this->db->join('mapel', 'mapel.id = pengajar.id_mapel');
        $this->db->join('kelas', 'kelas.id = pengajar.id_kelas');
        $this->db->order_by('pengajar.id_mapel', 'asc');
        return $this->db->get()->result_array();
    }

    // dapatkan semua mapel yang diajarkan berdasarkan id_guru dan id_tahun 
    function get_mapel_by_id_guru_group_by_id_mapel($id_guru)
    {
        $this->db->select('pengajar.id as id, pengajar.id_guru, mapel.id as id_mapel, mapel.nama as nama_mapel, mapel.kode as kode_mapel, kelas.nama as nama_kelas');
        $this->db->from('pengajar');
        $this->db->where('pengajar.id_guru ='.$id_guru);
        $this->db->where('pengajar.id_tahun ='.$_SESSION['id_tahun_pelajaran']);
        $this->db->join('mapel', 'mapel.id = pengajar.id_mapel');
        $this->db->join('kelas', 'kelas.id = pengajar.id_kelas');
        $this->db->group_by('id_mapel');
        $this->db->order_by('pengajar.id_mapel', 'asc');
        return $this->db->get()->result_array();
    }

    // dapatkan kelas berdasarkan id mapel, id guru, dan id tahun
    function get_kelas_by_id_mapel_id_guru_id_tahun($id_mapel)
    {
        
    }
}