<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Profil_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get profil by id
     */
    function get_profil($id)
    {
        return $this->db->get_where('profil',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all profil
     */
    function get_all_profil()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('profil')->result_array();
    }
        
    /*
     * function to add new profil
     */
    function add_profil($params)
    {
        $this->db->insert('profil',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update profil
     */
    function update_profil($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('profil',$params);
    }
    
    /*
     * function to delete profil
     */
    function delete_profil($id)
    {
        return $this->db->delete('profil',array('id'=>$id));
    }

    /*
    * function count rows
    */
    function count_row()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('profil')->num_rows();
    }
}