<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rombel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rombel by id
     */
    function get_rombel($id)
    {
        return $this->db->get_where('rombel',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all rombel
     */
    function get_all_rombel()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('rombel')->result_array();
    }
        
    /*
     * function to add new rombel
     */
    function add_rombel($params)
    {
        // $this->db->insert('rombel',$params);
        // return $this->db->insert_id();
        return $this->db->insert_batch('rombel', $params);

    }
    
    /*
     * function to update rombel
     */
    function update_rombel($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('rombel',$params);
    }
    
    /*
     * function to delete rombel
     */
    function delete_rombel($id)
    {
        return $this->db->delete('rombel',array('id'=>$id));
    }

    /*
     * Get all siswa
     */
    function get_all_siswa()
    {
        // $this->db->order_by('id', 'desc');
        // return $this->db->get('siswa')->result_array();
        return $this->db->query("SELECT * FROM siswa WHERE NOT EXISTS (SELECT * FROM rombel WHERE siswa.id = rombel.id_siswa)")->result_array();
    }

    /*
     * Get all kelas
     */
    function get_all_kelas()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('kelas')->result_array();
    }
}