<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Siswa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get siswa by id
     */
    function get_siswa($id)
    {
        return $this->db->get_where('siswa',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all siswa
     */
    function get_all_siswa()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('siswa')->result_array();
    }
        
    /*
     * function to add new siswa
     */
    function add_siswa($params)
    {
        $this->db->insert('siswa',$params);
        // return $this->db->insert_id();
    }
    
    /*
     * function to update siswa
     */
    function update_siswa($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('siswa',$params);
    }
    
    /*
     * function to delete siswa
     */
    function delete_siswa($id)
    {
        return $this->db->delete('siswa',array('id'=>$id));
    }

    /*
    * function count rows
    */
    function count_row()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('siswa')->num_rows();
    }
}