<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tahun_pelajaran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tahun_pelajaran by id
     */
    function get_tahun_pelajaran($id)
    {
        return $this->db->get_where('tahun_pelajaran',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tahun_pelajaran
     */
    function get_all_tahun_pelajaran()
    {
        $this->db->select('t.id as id, t.tahun as tahun, t.semester as semester, t.tanggal_rapor as tanggal_rapor, g.nama_lengkap as kepsek');
        $this->db->from('tahun_pelajaran as t');
        $this->db->join('guru as g', 't.id_kepsek = g.id');
        $this->db->order_by('id', 'desc');
        return $this->db->get()->result_array();
        // return $this->db->get('tahun_pelajaran')->result_array();
    }
        
    /*
     * function to add new tahun_pelajaran
     */
    function add_tahun_pelajaran($params)
    {
        $this->db->insert('tahun_pelajaran',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tahun_pelajaran
     */
    function update_tahun_pelajaran($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tahun_pelajaran',$params);
    }
    
    /*
     * function to delete tahun_pelajaran
     */
    function delete_tahun_pelajaran($id)
    {
        return $this->db->delete('tahun_pelajaran',array('id'=>$id));
    }
}