<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Walikelas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get walikelas by id
     */
    function get_walikelas($id)
    {
        return $this->db->get_where('walikelas',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all walikelas
     */
    function get_all_walikelas()
    {
        $this->db->select('walikelas.*, kelas.nama as nama_kelas, guru.nama_lengkap as nama_guru');
        $this->db->join('kelas', 'kelas.id = walikelas.id_kelas');
        $this->db->join('guru', 'guru.id = walikelas.id_guru');
        $this->db->where('walikelas.id_tahun', $_SESSION['id_tahun_pelajaran']);
        $this->db->order_by('id', 'desc');
        return $this->db->get('walikelas')->result_array();
    }
        
    /*
     * function to add new walikelas
     */
    function add_walikelas($params)
    {
        $this->db->insert('walikelas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update walikelas
     */
    function update_walikelas($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('walikelas',$params);
    }
    
    /*
     * function to delete walikelas
     */
    function delete_walikelas($id)
    {
        return $this->db->delete('walikelas',array('id'=>$id));
    }

    function get_all_kelas()
    {
        // dapatkan kelas yang belum memiliki walikelas
        return $this->db->query("SELECT * FROM kelas WHERE NOT EXISTS (SELECT * FROM walikelas WHERE kelas.id = walikelas.id_kelas AND walikelas.id_tahun = ".$_SESSION['id_tahun_pelajaran'].")")->result_array();
        
    }
}